---
- name: Patch and reboot API servers
  hosts: api_servers
  become: true

  tasks:
    - name: Update all packages (Debian/Ubuntu)
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Update all packages (RedHat)
      ansible.builtin.dnf:
        name: '*'
        state: present
      when: ansible_os_family == "RedHat"

    - name: Reboot if needed
      ansible.builtin.reboot:
        reboot_timeout: 300
        pre_reboot_delay: 10
        post_reboot_delay: 30
        test_command: whoami